# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub GraphQL API Query
      # You may pin to the exact commit or the version.
      # uses: octokit/graphql-action@5b35793a23d626e7528da63fc3b47a5bc06b628c
      uses: octokit/graphql-action@v2.2.1
      id: get_latest_pr
      with:
        query: |
              query release($owner:String!,$repo:String!) {
                repository(owner:$owner, name:$repo) {
                  pullRequests(last:1) {
                    nodes {
                      number
                      title
                      author {
                        login
                      }
                    }
                  }
                }
              }
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Send chat to group
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          curl -v --data-urlencode "group_id=$GROUPNO" --data-urlencode "message=$MSG" "http://127.0.0.1:5700/send_group_msg"
        script_stop: true
        envs: GROUPNO,MSG 
      env:
        GROUPNO: ${{ secrets.NOTIFY_GROUP_ID }}
        MSG: ${{ format('{0} proposed new things #{1} >> {2}', fromJSON(steps.get_latest_pr.outputs.data).repository.pullRequests.nodes[0].author.login,fromJSON(steps.get_latest_pr.outputs.data).repository.pullRequests.nodes[0].number,fromJSON(steps.get_latest_pr.outputs.data).repository.pullRequests.nodes[0].title) }}

